app <- ShinyDriver$new("../../")
app$snapshotInit("test-signup-allfields")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sign_up = "click")
app$setInputs(sidebarCollapsed = TRUE)
app$setInputs(email = "11")
app$setInputs(submitted = "click")
app$snapshot()
app$setInputs(phonNum = "1")
app$setInputs(submitted = "click")
app$setInputs(firstName = "1")
app$setInputs(submitted = "click")
app$setInputs(midName = "1")
app$setInputs(submitted = "click")
app$setInputs(lastName = "1")
app$setInputs(submitted = "click")
app$setInputs(mailAdd = "1")
app$setInputs(submitted = "click")
app$setInputs(occupation = "1")
app$setInputs(submitted = "click")
app$setInputs(userName_su = "1")
app$setInputs(submitted = "click")
app$setInputs(userName_su = "11")
app$setInputs(submitted = "click")
app$snapshot()
app$setInputs(passwd_su = "1")
app$setInputs(passwd_su = "11")
app$setInputs(submitted = "click")
app$snapshot()
