app <- ShinyDriver$new("../../")
app$snapshotInit("test-signin-nomatch-noexiting-login")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sign_in = "click")
app$setInputs(sidebarCollapsed = TRUE)
app$snapshot()
app$setInputs(userName = "dafadfa")
app$setInputs(loggedIn = "click")
app$snapshot()
app$setInputs(passwd = "da")
app$setInputs(loggedIn = "click")
app$setInputs(userName = "22")
app$setInputs(loggedIn = "click")
app$setInputs(userName = "2")
app$setInputs(loggedIn = "click")
app$snapshot()
app$setInputs(loggedIn = "click")
app$snapshot()
app$setInputs(loggedIn = "click")
app$setInputs(passwd = "d")
app$setInputs(loggedIn = "click")
app$setInputs(userName = "")
app$setInputs(userName = "1")
app$setInputs(passwd = "d1")
app$setInputs(passwd = "d")
app$setInputs(passwd = "1")
app$setInputs(loggedIn = "click")
app$snapshot()
