app <- ShinyDriver$new("../../")
app$snapshotInit("test-retrieve")

app$setInputs(sidebarCollapsed = FALSE)
app$snapshot()
app$setInputs(retrieve = "click")
app$setInputs(sidebarCollapsed = TRUE)
app$snapshot()
app$setInputs(email_rtr = "1")
app$setInputs(email_rtr = "12")
app$snapshot()
app$setInputs(retrieved = "click")
app$snapshot()
app$setInputs(login_from_info = "click")
app$setInputs(userName = "2")
app$setInputs(passwd = "2")
app$setInputs(loggedIn = "click")
app$snapshot()
