app <- ShinyDriver$new("../../")
app$snapshotInit("test-signup-signin")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sign_up = "click")
app$setInputs(sidebarCollapsed = TRUE)
app$setInputs(email = "111")
app$setInputs(phonNum = "1")
app$setInputs(firstName = "q")
app$setInputs(midName = "q")
app$setInputs(mailAdd = "q")
app$setInputs(lastName = "q")
app$setInputs(userName_su = "q")
app$setInputs(occupation = "q")
app$setInputs(passwd_su = "q")
app$setInputs(submitted = "click")
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
